// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import DragController from "./drag_controller"
application.register("drag", DragController)

import EditpostController from "./editpost_controller"
application.register("editpost", EditpostController)

import PhotoTileController from "./photo_tile_controller"
application.register("photoTile", PhotoTileController)